project:
  type: website

website:
  title: "Voice-emotion-classification"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - about.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
